name: 'FRC code tests'
description: 'Automatically build and test your FRC robot projects'
author: 'ewpratten'
icon: 'check-square'
color: 'purple'
inputs: 
  build_mode:
    description: 'What should be run? One of: ["all", "build", "unit_test"]'
    default: 'all'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.build_mode }}
