name: 'FRC Build & Test'
description: 'Automatically build and test your FRC robot projects'
branding:
  icon: 'check-square'
  color: 'green'
author: 'jetpham'

inputs:
  build_mode:
    description: 'What should be run? One of: ["all", "build", "unit_test"]'
    default: 'all'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.build_mode }}
